# Generated by Django 5.1.3 on 2024-12-07 08:11

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactuspage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': '关于我们'},
        ),
        migrations.AlterModelOptions(
            name='branddesignpage',
            options={'verbose_name': '品牌设计'},
        ),
        migrations.AlterModelOptions(
            name='contactuspage',
            options={'verbose_name': '联系我们'},
        ),
        migrations.AlterModelOptions(
            name='copywriterpage',
            options={'verbose_name': '文案策划'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': '首页'},
        ),
        migrations.AlterModelOptions(
            name='industrycasespage',
            options={'verbose_name': '行业案例'},
        ),
        migrations.AlterModelOptions(
            name='meetingplanningpage',
            options={'verbose_name': '会议策划'},
        ),
        migrations.AlterModelOptions(
            name='newspage',
            options={'verbose_name': '新闻动态'},
        ),
        migrations.AlterModelOptions(
            name='workscasespage',
            options={'verbose_name': '作品案例'},
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.CreateModel(
            name='PageGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='home.homepage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
