# Generated by Django 5.1.3 on 2024-12-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_aboutpage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagegalleryimage',
            name='describe',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
