# Generated by Django 5.1.3 on 2024-12-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_pagegalleryimage_describe'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='describe',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='pagegalleryimage',
            name='industry',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
