# Generated by Django 5.1.3 on 2024-12-09 04:36

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_caseitempage_remove_homepage_describe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagegalleryimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.caseitempage'),
        ),
    ]
