# Generated by Django 5.1.3 on 2024-12-11 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_caseitempage_body'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuspage',
            name='addr',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='email',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='mobile',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='qrcode_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='tel',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
