# Generated by Django 5.1.3 on 2024-12-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_contactuspage_addr_contactuspage_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseitempage',
            name='is_home_item',
            field=models.BooleanField(default=False),
        ),
    ]
