# Generated by Django 5.1.3 on 2024-12-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_caseitempage_is_home_item_row0_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caseitempage',
            old_name='is_home_item_row0',
            new_name='is_home_item_left',
        ),
        migrations.RenameField(
            model_name='caseitempage',
            old_name='is_home_item_row1_left',
            new_name='is_home_item_right',
        ),
        migrations.RemoveField(
            model_name='caseitempage',
            name='is_home_item_row1_right',
        ),
        migrations.AddField(
            model_name='caseitempage',
            name='is_home_item_row',
            field=models.IntegerField(default=0),
        ),
    ]
