# Generated by Django 5.1.3 on 2024-12-13 05:39

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_is_home_item_row0_caseitempage_is_home_item_left_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTitle',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('describe', wagtail.fields.StreamField([('p', 0)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {})})),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='heads', to='home.homepage')),
            ],
            options={
                'verbose_name': '首页头部轮播',
            },
            bases=('wagtailcore.page',),
        ),
    ]
