# Generated by Django 5.1.3 on 2024-12-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_hometitle_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hometitle',
            name='describe',
        ),
        migrations.AddField(
            model_name='hometitle',
            name='text_row1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='hometitle',
            name='text_row2',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
