# Generated by Django 5.1.3 on 2024-12-13 06:03

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_hometitle_describe_hometitle_text_row1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometitle',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heads', to='home.homepage'),
        ),
    ]
