# Generated by Django 5.1.3 on 2024-12-13 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_hometitle_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hometitle',
            name='page',
        ),
    ]
