name: Docker Image CI
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
env:
  IMAGE_NAME: mycms
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Copy requirements
        run: cat requirements.lock > ./mysite/requirements.txt
      - name: Set up QEMU (optional, for emulating architectures)
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ IMAGE_NAME }}:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
